# spring properties
spring:
    aplication:
        name: customer-client-service #identify this application
    freemarker:
        enabled: false   #Ignore Eureka dashboard FreeMarker templates
    thymeleaf:
        cache: false
        prefix: classpath:/templates/   #Trailing / mandatory
                            #template location for this aplication onlyy
#Map the error path to error template (for Thymeleaf)
error:
    path=/error

# Discovery Server Access
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/

#HTTP Server
server:
    port: 3333 #HTTP (Tomcat) port